version: '3.2'

services:
  db:
    image: postgres:14.4
    container_name: test_danger_db
    environment:
      - POSTGRES_DB=test_danger_development
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.7
    container_name: test_danger_redis
    ports:
      - "6379:6379"
